<Project>

  <!-- Inject the device or simulator framework as a transitive NativeReference. -->

  <PropertyGroup>
    <FFAudioFrameworks>$(MSBuildThisFileDirectory)../../native/ios</FFAudioFrameworks>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'ios' And $(RuntimeIdentifier.StartsWith('iossimulator'))">
    <NativeReference Include="$(FFAudioFrameworks)/ios-simulator/ffaudio.framework">
      <Kind>Framework</Kind>
    </NativeReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'ios' And '$(RuntimeIdentifier)' != '' And !$(RuntimeIdentifier.StartsWith('iossimulator'))">
    <NativeReference Include="$(FFAudioFrameworks)/ios-device/ffaudio.framework">
      <Kind>Framework</Kind>
    </NativeReference>
  </ItemGroup>

</Project>
